model_name: "CleanUNet2"

# data
snr_lower: 0.1
snr_upper: 2.0

# loss function
loss: 'mae'
frame_lengths: [100]
frame_steps: [24]
fft_sizes: [126]
stft_lambda: 1.0
sc_lambda: 1.0
mag_lambda: 1.0

# training
batch_size: 256
lr: 0.0002
epochs: 4000
clipnorm: 1e9

val_freq: 1e9
lr_schedule: True

# architecture
clean_specnet_path: /cluster/scratch/ckeusch/dsl-as24-challenge-3/outputs/2024-12-10/14-26-52/checkpoints/2.pth
clean_specnet:
  n_channels: 3
  n_layers: 3
  channel_base: 8
  dropout: 0.0

clean_unet:
  # encoder/decoder settings   
  channels_input: 3 
  channels_output: 3      
  channels_H: 64
  encoder_n_layers: 5
  kernel_size: 5
  max_H: 768

  # transformer settings
  tsfm_n_layers: 3
  tsfm_n_head: 8
  tsfm_d_model: 512
  tsfm_d_inner: 1024