model_name: "CleanUNet"

# data
snr_lower: 0.1
snr_upper: 2.0
random: True
subset: null
pure_noise: False

# training
batch_size: 128
lr: 0.001
epochs: 100
clipnorm: 1e9
# checkpoint_model: '/cluster/scratch/ckeusch/dsl-as24-challenge-3/outputs/2024-12-01/12-02-44/model.pth'
checkpoint_model: null

# Early Stopping callback
patience: 5
min_delta: 10

# Checkpoint Logger callback
log_checkpoints: True
checkpoint_freq: 5000

# learning rate scheduler
lr_schedule: False

# validation frequency
val_freq: 10

# 'clean_unet_loss' for mae + STFT loss 
loss: 'clean_unet_loss'
# frame_lengths: [23, 46, 10]
# frame_steps: [5, 10, 2]
# fft_sizes: [64, 128, 32]
frame_lengths: [100]
frame_steps: [16] 
fft_sizes: [127]
stft_lambda: 1.0
sc_lambda: 0.5
mag_lambda: 0.5

architecture:
  # encoder/decoder settings   
  channels_input: 3 
  channels_output: 3
  dropout: 0.0
  channels_H: 8
  encoder_n_layers: 5
  kernel_size: 4
  stride: 2
  max_H: 768

  # transformer settings
  tsfm_n_layers: 1
  tsfm_n_head: 4
  tsfm_d_model: 32
  tsfm_d_inner: 64


