model_name: "CleanUNet"
use_csv: True
train_pytorch: True
load_dummy: False

# baseline
use_baseline: False
channel_base: 8
channel_dims: [1,2,4,8]

# data
snr_lower: 0.1
snr_upper: 2.0
event_shift_start: 5000

# training
batch_size: 256
lr: 0.001
epochs: 100

# Early Stopping callback
patience: 5
# Checkpoint Logger callback
log_checkpoints: False
checkpoint_freq: 10
# learning rate scheduler
lr_schedule: False
decay_steps: 1920
warmup_target: 0.1
alpha: 0.0
warmup_steps: 80
# reduce learning rate plateau callback
reduce_lr_plateau: True
min_lr: 0.0001
factor: 0.2
plateau_patience: 3

seed: 123
clipnorm: null

# use 'stft' for multi-resolution stft loss
loss: 'stft'

signal_length: 6120
frame_steps: [2, 4, 9]
frame_lengths: [9, 23, 46]
fft_sizes: [19, 40, 78]
# frame_lengths: [100]
# frame_steps: [24]
# fft_sizes: [126]
stft_lambda: 1.0
sc_lambda: 0.5
mag_lambda: 0.5

# architecture
channels_input: 3 
channels_output: 3
dropout: 0.0

# encoder/decoder settings   
use_raglu: False        
channels_H: 8
max_H: 768
encoder_n_layers: 8
kernel_size: 3
stride: 2
kernel_sizes: [9, 9, 7, 7, 5, 5, 3, 3]

# choices: 'lstm', 'transformer', null
bottleneck: 'lstm'

# transformer settings
tsfm_n_layers: 1
tsfm_n_head: 4
tsfm_d_model: 64
tsfm_d_inner: 128