model_name: "CleanUNet"
load_checkpoint: False

# dataset
subset: null

# training
batch_size: 256
lr: 0.0002
epochs: 3000
use_amp: False
clipnorm: 1e9

patience: 1e9
min_delta: 1

log_checkpoints: False
checkpoint_freq: 200

lr_schedule: True

val_freq: 10

# 'mae': L1 loss in time domain
# 'stft': STFT Log Magnitude Loss + Spectogram Loss 
# 'clean_unet_loss': mae + 0.5 * stft  
loss: 'mae'
# frame_lengths: [23, 46, 10]
# frame_steps: [5, 10, 2]
# fft_sizes: [64, 128, 32]
frame_lengths: [100]
frame_steps: [16] 
fft_sizes: [127]
stft_lambda: 1.0
sc_lambda: 0.5
mag_lambda: 0.5

architecture:
  # encoder/decoder settings   
  channels_input: 3 
  channels_output: 3
  dropout: 0.0
  channels_H: 32
  encoder_n_layers: 5
  kernel_size: 4
  stride: 2
  max_H: 256

  #can be either 'lstm' or 'transformer'
  bottleneck: "transformer"
  # transformer settings
  tsfm_n_layers: 5
  tsfm_n_head: 8
  tsfm_d_model: 256
  tsfm_d_inner: 512


