model_name: "CleanUNet"
load_checkpoint: False

# dataset
subset: null

# training
batch_size: 512
lr: 0.0002
epochs: 100
use_amp: False
clipnorm: 1e9

patience: 1e9
min_delta: 1

log_checkpoints: True
checkpoint_freq: 20

lr_schedule: False

val_freq: 5

# 'mae': L1 loss in time domain
# 'stft': STFT Log Magnitude Loss + Spectogram Loss 
# 'clean_unet_loss': mae + 0.5 * stft  
loss: 'mae'
# frame_lengths: [23, 46, 10]
# frame_steps: [5, 10, 2]
# fft_sizes: [64, 128, 32]
frame_lengths: [100]
frame_steps: [16] 
fft_sizes: [127]
stft_lambda: 1.0
sc_lambda: 0.5
mag_lambda: 0.5

architecture:
  # encoder/decoder settings   
  channels_input: 3 
  channels_output: 3
  dropout: 0.0
  channels_H: 16
  encoder_n_layers: 6
  kernel_size: 4
  stride: 2
  max_H: 512

  #can be either 'lstm' or 'transformer'
  bottleneck: "transformer"
  # transformer settings
  tsfm_n_layers: 3
  tsfm_n_head: 8
  tsfm_d_model: 256
  tsfm_d_inner: 512


