model_name: "CleanUNet2"
clean_specnet: True
train_pytorch: True
use_metrics: False
load_dummy: False
seed: 123

# data
snr_lower: 0.1
snr_upper: 2.0
event_shift_start: 5000

# training
batch_size: 32
lr: 0.001
epochs: 100
clipnorm: null

# Early Stopping callback
patience: 10

# Checkpoint Logger callback
log_checkpoints: True
checkpoint_freq: 10

# learning rate scheduler
lr_schedule: False
decay_steps: 1920
warmup_target: 0.1
alpha: 0.0
warmup_steps: 80

# reduce learning rate plateau callback
reduce_lr_plateau: True
min_lr: 0.0001
factor: 0.2
plateau_patience: 3

# 'stft' for spectogram loss only
# 'mae' for L1 loss only
# 'clean_unet' for stft + mae loss 
loss: 'stft'

signal_length: 6120
frame_lengths: [100]
frame_steps: [24]
fft_sizes: [126]
stft_lambda: 1.0
sc_lambda: 1.0
mag_lambda: 1.0

# encoder/decoder settings   
channels_input: 3 
channels_output: 3
dropout: 0.0        
channels_H: 64
encoder_n_layers: 5
kernel_size: 4
max_H: 768

# transformer settings
tsfm_n_layers: 3
tsfm_n_head: 8
tsfm_d_model: 32
tsfm_d_inner: 512