model_name: "CleanUNet"

# data
snr_lower: 0.1
snr_upper: 2.0
event_shift_start: 5000
signal_length: 2048

# training
batch_size: 64
lr: 0.0001
epochs: 10
seed: 123

# loss can be either 'stft' or 'mae'
loss: 'mae'

# architecture
channels_input: 3 
channels_output: 3
dropout: 0.0

# encoder/decoder settings           
channels_H: 8
max_H: 768
encoder_n_layers: 4
kernel_size: 3
stride: 2

# transformer settings
tsfm_n_layers: 1
tsfm_n_head: 4
tsfm_d_model: 128
tsfm_d_inner: 256