model_name: "ColdDiffusion"
use_csv: True
# architecture
dim: 8
dim_multiples: [1, 2, 4]
attn_dim_head: 32
attn_heads: 4
resnet_norm_groups: 8

T: 50

# data
signal_length: 6144

# training 
continue_from_pretrained: False
pretrained_path: "/home/tlauner/DSLab/dsl-as24-challenge-3/outputs/2024-11-21/14-38-30/ColdDiffusion_lr_0.0005_e9.keras"
batch_size: 8
num_workers: 2
lr: 0.0005
epochs: 1
seed: 123

# testing
test_batch_size: 32