model_name: "ColdDiffusion"
use_csv: True
# architecture
dim: 16
dim_multiples: [1, 2, 4, 4, 8]
attn_dim_head: 32
attn_heads: 4
resnet_norm_groups: 8

# T: 50

# data
signal_length: 4096

# training 
continue_from_pretrained: True
pretrained_path: "/home/tlauner/DSLab/dsl-as24-challenge-3/outputs/2024-12-08/17-51-16/chkpt_epoch_15_20_cosine_cold_diffusion.pth"
batch_size: 32 
num_workers: 2
lr: 0.001
epochs: 25
seed: 123

# testing
test_batch_size: 32
sampling: True

# new
channels: 3
T: 20
scheduler_type: 'cosine'
s: 0.008
penalization: 3.0
