model_name: "ColdDiffusion"
use_csv: True
# architecture
dim: 32
dim_multiples: [1, 2, 4, 4, 8] # [1,2,4,4,8]
attn_dim_head: 64 #  32
attn_heads: 8 #  4
resnet_norm_groups: 8

# T: 50

# data
signal_length: 4096

# training 
continue_from_pretrained: False
pretrained_path: "/home/tlauner/DSLab/dsl-as24-challenge-3/outputs/2024-12-09/11-34-57/chkpt_epoch_26_20_cosine_cold_diffusion.pth"
batch_size: 32 
num_workers: 2
lr: 0.0005
epochs: 50
seed: 123

# testing
test_batch_size: 32
sampling: False

# new
channels: 3
T: 20
scheduler_type: 'cosine'
s: 0.008
penalization: 3.0
learned_sinusoidal_cond: False
