model_name: "ColdDiffusion"
use_csv: True
# architecture
dim: 8
dim_multiples: [1, 2, 4]
attn_dim_head: 32
attn_heads: 4
resnet_norm_groups: 1

T: 50

# data
signal_length: 4096

# training 
batch_size: 8
num_workers: 1
lr: 0.0005
epochs: 3
seed: 123

# loss can be either 'stft', 'mae' or 'mse'
loss_type: 'mae'
