model_name: "ColdDiffusion"
use_csv: True

# architecture
architecture:
  dim: 32
  dim_mults: [1, 2, 4, 4, 8] # [1,2,4,4,8]
  channels: 3
  learned_sinusoidal_cond: False
  attn_dim_head: 64 #  32
  attn_heads: 8 #  4
  resnet_block_groups: 8

# training 
epochs: 50
batch_size: 32 
lr: 0.0005
num_workers: 2
continue_from_pretrained: False
pretrained_path: "/home/tlauner/DSLab/dsl-as24-challenge-3/outputs/2024-12-09/11-34-57/chkpt_epoch_26_20_cosine_cold_diffusion.pth"

# testing
test_batch_size: 32
sampling: False

# new
T: 20
scheduler_type: 'cosine'
s: 0.008
penalization: 3.0
