model_name: "DeepDenoiser"
use_csv: True

# model architecture
channel_base: 8
n_layers: 3
dropout: 0.0

# data
snr_lower: 0.1
snr_upper: 2.0

# stft parameters
signal_length: 6120
frame_length: 100
frame_step: 24
fft_size: 126

# training 
batch_size: 64
lr: 0.001
use_lr_scheduler: False
epochs: 10
seed: 123





