model_name: "DeepDenoiser"
use_csv: True

# model architecture
channel_base: 8
n_layers: 6
dropout: 0.2

# data
snr_lower: 0.1
snr_upper: 2.0

# stft parameters
signal_length: 6120
frame_length: 100
frame_step: 24
fft_size: 126

# training 
batch_size: 256
lr: 0.001
epochs: 10
seed: 123




