model_name: "DeepDenoiser"

subset: null
random: True

snr_lower: 0.1
snr_upper: 2.0


architecture:
  n_channels: 3
  n_layers: 3
  channel_base: 8
  dropout: 0.0

  # STFT parameters
  n_fft: 127
  win_length: 100
  hop_length: 16

# Training parameters
batch_size: 128
epochs: 20
lr: 0.0001
clip_norm: 1e9

val_freq: 1