# model architecture
model_name: "DeepDenoiser"
channel_base: 8
n_layers: 5
dropout: 0.0

# stft parameters
signal_length: 6120
frame_length: 100
frame_step: 24
fft_size: 126

# training 
batch_size: 32
lr: 1e-4
epochs: 5
seed: 123
device: 'cuda'
save_every_x_epoch: 5

# testing
model_path: 'C:\Users\cleme\ETH\Master\DataLab\dsl-as24-challenge-3\models\DeepDenoiser\model_at_epoch_4.keras'


