model_name: 'WaveDecompNet'
use_csv: True

# model architecture
channel_base: 8
n_layers: 5
dropout: 0.0
n_lstm_layers: 1

# loss 
signal_weight: 0.8

# SNR
snr_lower: 0.1
snr_upper: 2.0

signal_length: 2048

# training 
batch_size: 256
lr: 0.001
epochs: 5
seed: 123


