defaults: 
  - _self_
  - model: cleanunet
  - user: clemens

seed: 123

# data properties
trace_length: 4096
random: True
snr_lower: 0.1
snr_upper: 2.0

# STFT properties
n_fft: 127
hop_length: 16
win_length: 1000

# TODO: add ColdDiffusion to get_trained_model function
# diffusion model settings
T: 20
dim: 32
dim_multiples: [1, 2, 4, 4, 8]
attn_dim_head: 64 #  32
attn_heads: 8 #  4
resnet_norm_groups: 8
channels: 3
scheduler_type: 'cosine'
s: 0.008
penalization: 3.0
learned_sinusoidal_cond: False

# butterworth settings
freq_range: [1, 45]
sampling_rate: 100

snrs: [0.1, 0.3, 0.5, 0.7, 1.0, 1.2, 1.5, 1.8, 2.0, 2.5, 3.5]

training: False
test: False
predictions: False
inference_speed:
  test: False
  warmup_iterations: 5
  timing_iterations: 20
wilcoxon_test: False
plot:
  models: ["Butterworth", "DeepDenoiser", "CleanUNetTransformer", "ColdDiffusion"]
  metrics: False
  channel_idx: 0
  #models: ["CleanUNetTransformer", "CleanUNetLSTM"]
  n_examples: 10
  visualization: True
  overlay_plot:
    plot: False
    specific: [[24, 0.5], [26, 1.5], [6, 2.5]] # (idx_example, snr)
    # specific: null
    # range: [30, 60] # [6000 - lower, 6000 + upper] 
    # range 
    range: null
    use_overlay: False
    compare_clean: False
    opacity: 0.8
  training_run:
    plot: False
  dayplot: False








