defaults: 
  - _self_
  - model: deepdenoiser

wandb: False
tuner: True
training: False

snrs: [0.1, 0.5, 1.0]
size_testset: 10

data:
  signal_path: 'C:\Users\cleme\ETH\Master\DataLab\dsl-as24-challenge-3\data\signal\'
  noise_path: 'C:\Users\cleme\ETH\Master\DataLab\dsl-as24-challenge-3\data\noise\'





