defaults: 
  - _self_
  - model: cleanunet
  - user: clemens

seed: 123

# data properties
trace_length: 4096
random: False

# butterworth settings
butterworth_range: [1, 45]
sampling_rate: 100

training: True
test: False
plot:
  metrics: False
  channel_idx: 0
  n_examples: 10
  visualization: False
  overlay_plot: False

snrs: [0.1, 0.3, 0.5, 0.7, 1.0, 1.2, 1.5, 1.8, 2.0, 2.5, 3.5]







