defaults: 
  - _self_
  - model: cleanunet
  - user: clemens
  # - submitit_slurm
  # - override hydra/launcher: submitit_slurm

seed: 123
trace_length: 6120
tuner: False
use_optuna: False
n_trials: 100
training: False
# can be 'accelerate', 'dataparallel' or null
# multi_gpu: 'accelerate'
multi_gpu: null 
test: True
plot:
  metrics: True
  visualization: False
  n_examples: 10
  vis_freq: 5

snrs: [0.1, 0.3, 0.5, 0.7, 1.0, 1.2, 1.5, 1.8, 2.0, 2.5, 3.5]
size_testset: 500







