defaults: 
  - _self_
  - model: cleanunet
  - user: clemens

tuner: False
use_optuna: False
n_trials: 100
training: True
test: False
plot:
  metrics: False
  visualization: False
  vis_freq: 5
  n_examples: 5

snrs: [0.1, 0.3, 0.5, 0.7, 1.0]
size_testset: 500





